import type { Metadata } from "next";
import { Inter, Intel_One_Mono } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/sonner";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const interMono = Intel_One_Mono({
  variable: "--font-inter-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${interMono.variable} antialiased`}>
        {children}
        <Toaster closeButton={true} position="top-right" richColors={true} />
      </body>
    </html>
  );
}
